# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode13.3
env:
  matrix:
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone 11'
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone 8'
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ServiceNetwork.xcworkspace -scheme ServiceNetwork-Example -sdk iphonesimulator13.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
